### ISSUE TITLE
Reporte Architect

### ISSUE THREAD

**Issue by Sandoval6** [SistemasTecTlaxiaco/actividad-3-practica-architect-Sandoval6#1]
[Architect_12.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-Sandoval6/files/12554858/Architect_12.pdf)

**Comment by isaireyesp1** [comment]
Portada : 22
Procedimiento : 25
Figuras, ilustraciones y fotografías.: 25
Resultados y conclusiones :22
calificacion : 94 = 18.8

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
